# 💽 Lecture 5 (Part 2, Data Storage Types) – Data 100, Spring 2026

[Acknowledgments Page](https://ds100.org/sp26/acks/)

In [1]:
import numpy as np
import polars as pl

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
#%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 9)

sns.set()
sns.set_context('talk')
np.set_printoptions(threshold=20, precision=2, suppress=True)
pl.Config.set_tbl_rows(30)
pl.Config.set_tbl_cols(-1)
# Use 2 decimal places for floats
pl.Config.set_float_precision(2)

# Silence some spurious seaborn warnings
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)


<br><br><br>

---

## 🤹‍♀️ File Formats Other than CSV

There are many file types for storing structured data: CSV, TSV, JSON, XML, ASCII, SAS...
* In lecture, we will cover JSON since `Polars` supports it out-of-box.

<br> <br>

---


### 🪆 JSON (JavaScript Object Notation)

The [congress.gov API](https://gpo.congress.gov/#/) (Application Programming Interface) provides data about the activities and members of the United States Congress (i.e., the House of Representatives and the Senate).

- Click the link above to see the kinds of information provided by the API. 

<br>

To get a JSON file containing information about the current members of Congress from California, you could use the following **API call**:

- `https://api.congress.gov/v3/member/CA?api_key=[INSERT_KEY]&limit=250&format=json&currentMember=True`

- You can instantly sign up for a congress.gov **API key** [here](https://gpo.congress.gov/sign-up/). Once you have your key, replace `[INSERT_KEY]` above with your key, and enter the API call as a URL in your browser. What happens? 

- Once the JSON from the API call is visible in your browser, you can click `File` --> `Save Page As` to save the JSON file to your coputer.

- Coarsely, API keys are used to track how much a given user engages with the API. There might be limits to the number of API calls (e.g., congress.gov API limits to 5,000 calls per hour), or a cost for API calls (e.g., using the OpenAI API for programmatically using ChatGPT).

<br>

For convenience, the JSON file from the call above has already been downloaded for you and is saved at `data/ca-congress-members.json`.

#### 📁 File contents

Let's look at `data/ca-congress-members.json` in the JupyterLab Explorer.

- Right-click the file, and then click `Open With` --> `Editor`.

- You'll notice that JSON looks a lot like a Python dictionary.

- Berkeley, CA is in the 12th district. Can you find our representative in Congress?

> Note: In general, it's a good idea to check the file size before opening a file in JupyterLab. Very large files can cause crashes. See `os.path.getsize` [documentation](https://docs.python.org/3/library/os.path.html#os.path.getsize).

We can programmatically view the first couple lines of the file using the same functions we used with CSVs:

In [3]:
congress_file = "data/ca-congress-members.json"

# Inspect the first five lines of the file
with open(congress_file, "r") as f:
    for i, row in enumerate(f):
        print(row)
        if i >= 4: break

{

    "members": [

        {

            "bioguideId": "T000491",

            "depiction": {

#### 🐍 EDA: Digging into JSON with Python

JSON data closely matches the internal Python object model.  

- In the following cell, we import the entire JSON datafile into a Python dictionary using the `json` package.

In [4]:
import json

# Import the JSON file into Python as a dictionary
with open(congress_file, "rb") as f:
    congress_json = json.load(f)

type(congress_json)

dict

The `congress_json` variable is a dictionary encoding the data in the JSON file.

Below, we access the first element of the `members` element of the `congress_json` dictionary.

- This first element is also a dictionary (and there are more dictionaries inside of it!)

In [5]:
# Grab the list corresponding to the `members` key in the JSON dictionary, 
# and then grab the first element of this list.
# In a moment, we'll see how we knew to use the key `members`, and that
# the resulting object is a list.
congress_json['members'][0]

{'bioguideId': 'T000491',
 'depiction': {'attribution': 'Image courtesy of the Member',
  'imageUrl': 'https://www.congress.gov/img/member/6774606d0b34857ecc9091a9_200.jpg'},
 'district': 45,
 'name': 'Tran, Derek',
 'partyName': 'Democratic',
 'state': 'California',
 'terms': {'item': [{'chamber': 'House of Representatives',
    'startYear': 2025}]},
 'updateDate': '2025-01-21T18:00:52Z',
 'url': 'https://api.congress.gov/v3/member/T000491?format=json'}

How should we probe a nested dictionary like `congress_json`?

We can start by identifying the top-level **keys** of the dictionary:

In [6]:
# Grab the top-level keys of the JSON dictionary
congress_json.keys()

dict_keys(['members', 'pagination', 'request'])

Looks like we have three top-level keys: `members`, `pagination`, and `request`.

> You'll often see a top-level `meta` key in JSON files. This does not refer to Meta (formerly Facebook). Instead, it typically refers to metadata (data about the data).  Metadata are often maintained alongside the data.

Let's check the type of the `members` element:

In [7]:
type(congress_json['members'])

list

Looks like a list! What are the first two elements?

In [8]:
congress_json['members'][:2]

[{'bioguideId': 'T000491',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/6774606d0b34857ecc9091a9_200.jpg'},
  'district': 45,
  'name': 'Tran, Derek',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2025-01-21T18:00:52Z',
  'url': 'https://api.congress.gov/v3/member/T000491?format=json'},
 {'bioguideId': 'M001241',
  'depiction': {'attribution': 'Image courtesy of the Member',
   'imageUrl': 'https://www.congress.gov/img/member/67744ed90b34857ecc909155_200.jpg'},
  'district': 47,
  'name': 'Min, Dave',
  'partyName': 'Democratic',
  'state': 'California',
  'terms': {'item': [{'chamber': 'House of Representatives',
     'startYear': 2025}]},
  'updateDate': '2025-01-21T18:00:52Z',
  'url': 'https://api.congress.gov/v3/member/M001241?format=json'}]

More dictionaries! You can repeat the process above to traverse the nested dictionary.

You'll notice that each record of `congress_json['members']` looks like it could be a column of a DataFrame.

- The keys look a lot like column names, and the values could be the entries in each row.

<br> 

But, the two other elements of `congress_json` don't have the same structure as `congress_json['members']`.

- So, they probably don't belong in a DataFrame containing the members of Congress from CA.

- We'll see the implications of this inconsistency in the next section.

In [9]:
print(congress_json['pagination'])
print(congress_json['request'])

{'count': 54}
{'contentType': 'application/json', 'format': 'json'}

#### 🐻‍❄️ JSON with Polars

`Polars` has a built in function called `pl.read_json` for reading in JSON files.

- Uncomment the code below and see what happens.

In [10]:
# pl.read_json(congress_file)

Uh oh. That gives us a single row with three columns, each one holding a whole nested piece of the file.

- The code above imports the entire JSON file located at `congress_file` (`congress_json`), including `congress_json['pagination']` and `congress_json['request']`.

- We only want to make a DataFrame out of `congress_json['members']`, with one row per member.

This time, let's try converting the `members` element of `congress_json` to a DataFrame by using `pl.DataFrame`:

In [11]:
# Convert dictionary to DataFrame
congress_df = pl.DataFrame(congress_json['members'])
congress_df.head()

shape: (5, 9)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ bioguide ┆ depictio ┆ district ┆ name     ┆ partyNam ┆ state    ┆ terms    ┆ updateDa ┆ url      │
│ Id       ┆ n        ┆ ---      ┆ ---      ┆ e        ┆ ---      ┆ ---      ┆ te       ┆ ---      │
│ ---      ┆ ---      ┆ i64      ┆ str      ┆ ---      ┆ str      ┆ struct[1 ┆ ---      ┆ str      │
│ str      ┆ struct[2 ┆          ┆          ┆ str      ┆          ┆ ]        ┆ str      ┆          │
│          ┆ ]        ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ T000491  ┆ {"Image  ┆ 45       ┆ Tran,    ┆ Democrat ┆ Californ ┆ {[{"Hous ┆ 2025-01- ┆ https:// │
│          ┆ courtesy ┆          ┆ Derek    ┆ ic       ┆ ia       ┆ e of Rep ┆ 21T18:00 ┆ api.cong │
│          ┆ of the   ┆          ┆          ┆          ┆          ┆ resentat ┆ :52Z     ┆ ress.gov │
│          ┆ Member…  ┆          ┆          ┆          ┆          ┆ ives",…  ┆          ┆ /v3/me…  │
│ M001241  ┆ {"Image  ┆ 47       ┆ Min,     ┆ Democrat ┆ Californ ┆ {[{"Hous ┆ 2025-01- ┆ https:// │
│          ┆ courtesy ┆          ┆ Dave     ┆ ic       ┆ ia       ┆ e of Rep ┆ 21T18:00 ┆ api.cong │
│          ┆ of the   ┆          ┆          ┆          ┆          ┆ resentat ┆ :52Z     ┆ ress.gov │
│          ┆ Member…  ┆          ┆          ┆          ┆          ┆ ives",…  ┆          ┆ /v3/me…  │
│ K000400  ┆ {"Image  ┆ 37       ┆ Kamlager ┆ Democrat ┆ Californ ┆ {[{"Hous ┆ 2025-01- ┆ https:// │
│          ┆ courtesy ┆          ┆ -Dove,   ┆ ic       ┆ ia       ┆ e of Rep ┆ 21T18:00 ┆ api.cong │
│          ┆ of the   ┆          ┆ Sydney   ┆          ┆          ┆ resentat ┆ :52Z     ┆ ress.gov │
│          ┆ Member…  ┆          ┆          ┆          ┆          ┆ ives",…  ┆          ┆ /v3/me…  │
│ G000598  ┆ {"Image  ┆ 42       ┆ Garcia,  ┆ Democrat ┆ Californ ┆ {[{"Hous ┆ 2025-01- ┆ https:// │
│          ┆ courtesy ┆          ┆ Robert   ┆ ic       ┆ ia       ┆ e of Rep ┆ 21T18:00 ┆ api.cong │
│          ┆ of the   ┆          ┆          ┆          ┆          ┆ resentat ┆ :52Z     ┆ ress.gov │
│          ┆ Member…  ┆          ┆          ┆          ┆          ┆ ives",…  ┆          ┆ /v3/me…  │
│ K000397  ┆ {"Image  ┆ 40       ┆ Kim,     ┆ Republic ┆ Californ ┆ {[{"Hous ┆ 2025-01- ┆ https:// │
│          ┆ courtesy ┆          ┆ Young    ┆ an       ┆ ia       ┆ e of Rep ┆ 21T18:00 ┆ api.cong │
│          ┆ of the   ┆          ┆          ┆          ┆          ┆ resentat ┆ :52Z     ┆ ress.gov │
│          ┆ Member…  ┆          ┆          ┆          ┆          ┆ ives",…  ┆          ┆ /v3/me…  │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

We've successfully begun to rectangularize our JSON data!

<br><br><br>

**Instructor Note: Return to Slides!**

<br/>

---


## 🕰️ Temporality

Let's briefly look at how we can use the `Polars` `dt` accessors to work with dates/times in a dataset.

We will use the Berkeley Police Department (PD) Calls for Service dataset.

In [12]:
calls = pl.read_csv("data/Berkeley_PD_-_Calls_for_Service.csv")
calls.head()

shape: (5, 11)
┌─────────┬─────────┬────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬───────┐
│ CASENO  ┆ OFFENSE ┆ EVENTD ┆ EVENTT ┆ CVLEGE ┆ CVDOW ┆ InDbDa ┆ Block_ ┆ BLKADD ┆ City   ┆ State │
│ ---     ┆ ---     ┆ T      ┆ M      ┆ ND     ┆ ---   ┆ te     ┆ Locati ┆ R      ┆ ---    ┆ ---   │
│ i64     ┆ str     ┆ ---    ┆ ---    ┆ ---    ┆ i64   ┆ ---    ┆ on     ┆ ---    ┆ str    ┆ str   │
│         ┆         ┆ str    ┆ str    ┆ str    ┆       ┆ str    ┆ ---    ┆ str    ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ str    ┆        ┆        ┆       │
╞═════════╪═════════╪════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪═══════╡
│ 2101429 ┆ THEFT   ┆ 04/01/ ┆ 10:58  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 6       ┆ MISD.   ┆ 2021   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 12:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00 AM  ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2101439 ┆ THEFT   ┆ 04/01/ ┆ 10:38  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 1       ┆ MISD.   ┆ 2021   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 12:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00 AM  ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2109049 ┆ THEFT   ┆ 04/19/ ┆ 12:15  ┆ LARCEN ┆ 1     ┆ 06/15/ ┆ 2100   ┆ 2100   ┆ Berkel ┆ CA    │
│ 4       ┆ MISD.   ┆ 2021   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 12:00: ┆        ┆        ┆       ┆ 12:00: ┆ HASTE  ┆ HASTE  ┆        ┆       │
│         ┆ $950)   ┆ 00 AM  ┆        ┆        ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey, …  ┆        ┆        ┆       │
│ 2109020 ┆ THEFT   ┆ 02/13/ ┆ 17:00  ┆ LARCEN ┆ 6     ┆ 06/15/ ┆ 2600   ┆ 2600   ┆ Berkel ┆ CA    │
│ 4       ┆ FELONY  ┆ 2021   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (OVER   ┆ 12:00: ┆        ┆        ┆       ┆ 12:00: ┆ WARRIN ┆ WARRIN ┆        ┆       │
│         ┆ $950)   ┆ 00 AM  ┆        ┆        ┆       ┆ 00 AM  ┆ G ST   ┆ G ST   ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey…    ┆        ┆        ┆       │
│ 2109017 ┆ BURGLAR ┆ 02/08/ ┆ 6:20   ┆ BURGLA ┆ 1     ┆ 06/15/ ┆ 2700   ┆ 2700   ┆ Berkel ┆ CA    │
│ 9       ┆ Y AUTO  ┆ 2021   ┆        ┆ RY -   ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆         ┆ 12:00: ┆        ┆ VEHICL ┆       ┆ 12:00: ┆ GARBER ┆ GARBER ┆        ┆       │
│         ┆         ┆ 00 AM  ┆        ┆ E      ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey,…   ┆        ┆        ┆       │
└─────────┴─────────┴────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴───────┘

Looks like there are three columns with dates/times: `EVENTDT`, `EVENTTM`, and `InDbDate`. 

- `EVENTDT` stands for the **date** when the event took place

- `EVENTTM` stands for the **time of day** the event took place (in 24-hr format)

- `InDbDate` is the date this call is entered into the database.

We can convert these string columns to `datetime` objects using the `str.to_datetime` method.

In [13]:
# str.to_datetime() will try to work out the layout of the string on its own,
# and it gives up when the layout is ambiguous or unusual.
# It's good practice to specify the format of your datetimes.
# See the documentation and the `format` argument.

calls = calls.with_columns(
    pl.col("EVENTDT").str.to_datetime(format='%m/%d/%Y %I:%M:%S %p')
)

calls.head()

shape: (5, 11)
┌─────────┬─────────┬────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬───────┐
│ CASENO  ┆ OFFENSE ┆ EVENTD ┆ EVENTT ┆ CVLEGE ┆ CVDOW ┆ InDbDa ┆ Block_ ┆ BLKADD ┆ City   ┆ State │
│ ---     ┆ ---     ┆ T      ┆ M      ┆ ND     ┆ ---   ┆ te     ┆ Locati ┆ R      ┆ ---    ┆ ---   │
│ i64     ┆ str     ┆ ---    ┆ ---    ┆ ---    ┆ i64   ┆ ---    ┆ on     ┆ ---    ┆ str    ┆ str   │
│         ┆         ┆ dateti ┆ str    ┆ str    ┆       ┆ str    ┆ ---    ┆ str    ┆        ┆       │
│         ┆         ┆ me[μs] ┆        ┆        ┆       ┆        ┆ str    ┆        ┆        ┆       │
╞═════════╪═════════╪════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪═══════╡
│ 2101429 ┆ THEFT   ┆ 2021-0 ┆ 10:58  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 6       ┆ MISD.   ┆ 4-01   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2101439 ┆ THEFT   ┆ 2021-0 ┆ 10:38  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 1       ┆ MISD.   ┆ 4-01   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2109049 ┆ THEFT   ┆ 2021-0 ┆ 12:15  ┆ LARCEN ┆ 1     ┆ 06/15/ ┆ 2100   ┆ 2100   ┆ Berkel ┆ CA    │
│ 4       ┆ MISD.   ┆ 4-19   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ HASTE  ┆ HASTE  ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey, …  ┆        ┆        ┆       │
│ 2109020 ┆ THEFT   ┆ 2021-0 ┆ 17:00  ┆ LARCEN ┆ 6     ┆ 06/15/ ┆ 2600   ┆ 2600   ┆ Berkel ┆ CA    │
│ 4       ┆ FELONY  ┆ 2-13   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (OVER   ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ WARRIN ┆ WARRIN ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ G ST   ┆ G ST   ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey…    ┆        ┆        ┆       │
│ 2109017 ┆ BURGLAR ┆ 2021-0 ┆ 6:20   ┆ BURGLA ┆ 1     ┆ 06/15/ ┆ 2700   ┆ 2700   ┆ Berkel ┆ CA    │
│ 9       ┆ Y AUTO  ┆ 2-08   ┆        ┆ RY -   ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆         ┆ 00:00: ┆        ┆ VEHICL ┆       ┆ 12:00: ┆ GARBER ┆ GARBER ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆ E      ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey,…   ┆        ┆        ┆       │
└─────────┴─────────┴────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴───────┘

Now we can use the `dt` accessor on this column.

We can get the month:

In [14]:
# 1 - January, 2 - February, ..., 12 - December
calls["EVENTDT"].dt.month()

shape: (2_632,)
Series: 'EVENTDT' [i8]
[
	4
	4
	4
	2
	2
	12
	5
	3
	3
	3
	6
	3
	4
	5
	2
	…
	5
	1
	1
	2
	1
	2
	1
	4
	1
	4
	12
	2
	3
	4
	2
]

Which day of the week the date is on:

In [15]:
# 1 - Monday, 2 - Tuesday, ..., 7 - Sunday
calls["EVENTDT"].dt.weekday()

shape: (2_632,)
Series: 'EVENTDT' [i8]
[
	4
	4
	1
	6
	1
	6
	1
	7
	3
	3
	4
	1
	5
	5
	2
	…
	5
	4
	1
	2
	2
	1
	4
	1
	7
	6
	1
	3
	3
	6
	5
]

We can also sort by datetime:

In [16]:
# Sort the DataFrame by datetime to find the earliest call.
calls.sort("EVENTDT").head()

shape: (5, 11)
┌─────────┬─────────┬────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬───────┐
│ CASENO  ┆ OFFENSE ┆ EVENTD ┆ EVENTT ┆ CVLEGE ┆ CVDOW ┆ InDbDa ┆ Block_ ┆ BLKADD ┆ City   ┆ State │
│ ---     ┆ ---     ┆ T      ┆ M      ┆ ND     ┆ ---   ┆ te     ┆ Locati ┆ R      ┆ ---    ┆ ---   │
│ i64     ┆ str     ┆ ---    ┆ ---    ┆ ---    ┆ i64   ┆ ---    ┆ on     ┆ ---    ┆ str    ┆ str   │
│         ┆         ┆ dateti ┆ str    ┆ str    ┆       ┆ str    ┆ ---    ┆ str    ┆        ┆       │
│         ┆         ┆ me[μs] ┆        ┆        ┆       ┆        ┆ str    ┆        ┆        ┆       │
╞═════════╪═════════╪════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪═══════╡
│ 2009221 ┆ THEFT   ┆ 2020-1 ┆ 18:30  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ 800    ┆ 800    ┆ Berkel ┆ CA    │
│ 4       ┆ FROM    ┆ 2-17   ┆        ┆ Y -    ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ AUTO    ┆ 00:00: ┆        ┆ FROM   ┆       ┆ 12:00: ┆ SHATTU ┆ SHATTU ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆ VEHICL ┆       ┆ 00 AM  ┆ CK AVE ┆ CK AVE ┆        ┆       │
│         ┆         ┆        ┆        ┆ E      ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ e…     ┆        ┆        ┆       │
│ 2005737 ┆ GUN/WEA ┆ 2020-1 ┆ 22:18  ┆ WEAPON ┆ 4     ┆ 06/15/ ┆ 6200   ┆ 6200   ┆ Berkel ┆ CA    │
│ 3       ┆ PON     ┆ 2-17   ┆        ┆ S OFFE ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆         ┆ 00:00: ┆        ┆ NSE    ┆       ┆ 12:00: ┆ SAN    ┆ SAN    ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ PABLO  ┆ PABLO  ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ AVE    ┆ AVE    ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berke… ┆        ┆        ┆       │
│ 2005720 ┆ ASSAULT ┆ 2020-1 ┆ 16:50  ┆ ASSAUL ┆ 4     ┆ 06/15/ ┆ 2100   ┆ 2100   ┆ Berkel ┆ CA    │
│ 7       ┆ /BATTER ┆ 2-17   ┆        ┆ T      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ Y MISD. ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ SHATTU ┆ SHATTU ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ CK AVE ┆ CK AVE ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ …      ┆        ┆        ┆       │
│ 2005732 ┆ THEFT   ┆ 2020-1 ┆ 15:44  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ 1800   ┆ 1800   ┆ Berkel ┆ CA    │
│ 4       ┆ MISD.   ┆ 2-17   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ 4TH ST ┆ 4TH ST ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey,    ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ CA…    ┆        ┆        ┆       │
│ 2005757 ┆ BURGLAR ┆ 2020-1 ┆ 22:15  ┆ BURGLA ┆ 4     ┆ 06/15/ ┆ 1700   ┆ 1700   ┆ Berkel ┆ CA    │
│ 3       ┆ Y RESID ┆ 2-17   ┆        ┆ RY -   ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ ENTIAL  ┆ 00:00: ┆        ┆ RESIDE ┆       ┆ 12:00: ┆ STUART ┆ STUART ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆ NTIAL  ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey,…   ┆        ┆        ┆       │
└─────────┴─────────┴────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴───────┘

We can also do many things with the `dt` accessor like switching time zones and converting time back to UNIX/POSIX time. Check out the documentation on the [`.dt` accessor](https://docs.pola.rs/api/python/stable/reference/series/temporal.html) and [time series/date functionality](https://docs.pola.rs/user-guide/transformations/time-series/parsing/).

What type are datetime objects?

In [17]:
calls["EVENTDT"].dtype

Datetime(time_unit='us', time_zone=None)

`us` above stands for microseconds, the time unit `Polars` records by default.

- The other choices of time unit are milliseconds (`ms`) and nanoseconds (`ns`).

Under the hood, datetimes are integers representing the number of **microseconds** since 1/1/1970 UTC.

In [18]:
# datetimes are stored as integers representing number of
# microseconds since 1970-01-01
calls["EVENTDT"].cast(pl.Int64)

shape: (2_632,)
Series: 'EVENTDT' [i64]
[
	1617235200000000
	1617235200000000
	1618790400000000
	1613174400000000
	1612742400000000
	1608940800000000
	1620000000000000
	1615075200000000
	1617148800000000
	1614729600000000
	1623283200000000
	1616976000000000
	1618531200000000
	1622160000000000
	1612224000000000
	…
	1622160000000000
	1610582400000000
	1609718400000000
	1613433600000000
	1609804800000000
	1613952000000000
	1611187200000000
	1618790400000000
	1612051200000000
	1617408000000000
	1608508800000000
	1614124800000000
	1616544000000000
	1619222400000000
	1614297600000000
]

<br><br><br>

**Instructor Note: Return to Slides!**

<br/>

---


## 🤷 Faithfulness and missing values

To conclude, let's **very** briefly explore missingness in the Berkeley PD Calls for Service dataset.

Looking at the top of the dataframe, we can already see that there are missing values in the `BLKADDR` column.

In [19]:
calls.head()

shape: (5, 11)
┌─────────┬─────────┬────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬───────┐
│ CASENO  ┆ OFFENSE ┆ EVENTD ┆ EVENTT ┆ CVLEGE ┆ CVDOW ┆ InDbDa ┆ Block_ ┆ BLKADD ┆ City   ┆ State │
│ ---     ┆ ---     ┆ T      ┆ M      ┆ ND     ┆ ---   ┆ te     ┆ Locati ┆ R      ┆ ---    ┆ ---   │
│ i64     ┆ str     ┆ ---    ┆ ---    ┆ ---    ┆ i64   ┆ ---    ┆ on     ┆ ---    ┆ str    ┆ str   │
│         ┆         ┆ dateti ┆ str    ┆ str    ┆       ┆ str    ┆ ---    ┆ str    ┆        ┆       │
│         ┆         ┆ me[μs] ┆        ┆        ┆       ┆        ┆ str    ┆        ┆        ┆       │
╞═════════╪═════════╪════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪═══════╡
│ 2101429 ┆ THEFT   ┆ 2021-0 ┆ 10:58  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 6       ┆ MISD.   ┆ 4-01   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2101439 ┆ THEFT   ┆ 2021-0 ┆ 10:38  ┆ LARCEN ┆ 4     ┆ 06/15/ ┆ Berkel ┆ null   ┆ Berkel ┆ CA    │
│ 1       ┆ MISD.   ┆ 4-01   ┆        ┆ Y      ┆       ┆ 2021   ┆ ey, CA ┆        ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ (37.86 ┆        ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ 9058,  ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ -122.… ┆        ┆        ┆       │
│ 2109049 ┆ THEFT   ┆ 2021-0 ┆ 12:15  ┆ LARCEN ┆ 1     ┆ 06/15/ ┆ 2100   ┆ 2100   ┆ Berkel ┆ CA    │
│ 4       ┆ MISD.   ┆ 4-19   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (UNDER  ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ HASTE  ┆ HASTE  ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey, …  ┆        ┆        ┆       │
│ 2109020 ┆ THEFT   ┆ 2021-0 ┆ 17:00  ┆ LARCEN ┆ 6     ┆ 06/15/ ┆ 2600   ┆ 2600   ┆ Berkel ┆ CA    │
│ 4       ┆ FELONY  ┆ 2-13   ┆        ┆ Y      ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆ (OVER   ┆ 00:00: ┆        ┆        ┆       ┆ 12:00: ┆ WARRIN ┆ WARRIN ┆        ┆       │
│         ┆ $950)   ┆ 00     ┆        ┆        ┆       ┆ 00 AM  ┆ G ST   ┆ G ST   ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey…    ┆        ┆        ┆       │
│ 2109017 ┆ BURGLAR ┆ 2021-0 ┆ 6:20   ┆ BURGLA ┆ 1     ┆ 06/15/ ┆ 2700   ┆ 2700   ┆ Berkel ┆ CA    │
│ 9       ┆ Y AUTO  ┆ 2-08   ┆        ┆ RY -   ┆       ┆ 2021   ┆ BLOCK  ┆ BLOCK  ┆ ey     ┆       │
│         ┆         ┆ 00:00: ┆        ┆ VEHICL ┆       ┆ 12:00: ┆ GARBER ┆ GARBER ┆        ┆       │
│         ┆         ┆ 00     ┆        ┆ E      ┆       ┆ 00 AM  ┆ ST     ┆ ST     ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ Berkel ┆        ┆        ┆       │
│         ┆         ┆        ┆        ┆        ┆       ┆        ┆ ey,…   ┆        ┆        ┆       │
└─────────┴─────────┴────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴───────┘

We can use the `.is_null()` method to get a sense of how often values in `BLKADDR` are missing.

- `null` is how `Polars` records a missing entry.

In [20]:
# is_null() returns a Series of booleans indicating whether each element
# # in the Series is missing.
print(calls['BLKADDR'].is_null().head())

# The mean of a Series of booleans is the proportion of booleans that are True.
calls['BLKADDR'].is_null().mean()

shape: (10,)
Series: 'BLKADDR' [bool]
[
	true
	true
	false
	false
	false
	false
	false
	false
	false
	false
]

0.007598784194528876

It looks like missing values are actually quite rare: Only 0.8% of records are missing a value in `BLKADDR`.

Why are these values missing? 

- Again, looking at just the first few rows, we see that `null` values in `BLKADDR` appear to be accompanied by latitude/longitude coordinates in the `Block_Location` column.

- In all likelihood, missing values in `BLKADDR` probably correspond to locations that do not have a defined address in the officer's navigation or GPS system.

<br>

The best default approach here: Leave the rows with missing `BLKADDR` untouched, or replace the `null` values with a `MISSING` indicator.

- In the future, if we wanted to conduct an analysis of the streets where police incidents were most common, we might impute `BLKADDR` by using the nearest street, which we could identify with an external package.

<br>

For a very rough sense of missingness in each column of a DataFrame, you can use the `null_count()` method.

- Based on the output, it looks like the only column with missing values is `BLKADDR`.

In [21]:
# null_count() reports the number of missing entries in each column.
# Compare the count for BLKADDR to the total number of rows.
print(calls.height, "rows")
calls.null_count()

2632 rows

shape: (1, 11)
┌────────┬─────────┬─────────┬─────────┬─────────┬───────┬────────┬────────┬────────┬──────┬───────┐
│ CASENO ┆ OFFENSE ┆ EVENTDT ┆ EVENTTM ┆ CVLEGEN ┆ CVDOW ┆ InDbDa ┆ Block_ ┆ BLKADD ┆ City ┆ State │
│ ---    ┆ ---     ┆ ---     ┆ ---     ┆ D       ┆ ---   ┆ te     ┆ Locati ┆ R      ┆ ---  ┆ ---   │
│ u32    ┆ u32     ┆ u32     ┆ u32     ┆ ---     ┆ u32   ┆ ---    ┆ on     ┆ ---    ┆ u32  ┆ u32   │
│        ┆         ┆         ┆         ┆ u32     ┆       ┆ u32    ┆ ---    ┆ u32    ┆      ┆       │
│        ┆         ┆         ┆         ┆         ┆       ┆        ┆ u32    ┆        ┆      ┆       │
╞════════╪═════════╪═════════╪═════════╪═════════╪═══════╪════════╪════════╪════════╪══════╪═══════╡
│ 0      ┆ 0       ┆ 0       ┆ 0       ┆ 0       ┆ 0     ┆ 0      ┆ 0      ┆ 20     ┆ 0    ┆ 0     │
└────────┴─────────┴─────────┴─────────┴─────────┴───────┴────────┴────────┴────────┴──────┴───────┘

<br><br><br>

**Instructor Note: Return to Slides!**